name: Java Tests with Maven

on:
  push:
    branches:
      - master
      - mood-tracker
      - mood-tracker-tests
      - testing-mood-entry
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Unit Tests
        run: mvn test

      - name: Report Test Results
        if: always()
        run: |
          echo "Test Results Summary:"
          cat target/surefire-reports/*.txt || echo "No test reports found"